### PR TITLE
A working version for review

### PR DESCRIPTION
**Pull request by amalfra**
Initial version

### CODE REVIEW

**Comment by lalitpatel** [comment]
Hi @amalfra, thanks for sending the assignment. We will review it over the weekend and get back to you

**Comment by adamstep** [comment]
Hi @amalfra , I tested out the code and overall it worked well, but I noticed a couple of issues:
- If I add one team member, the main screen says "You have 1 team members", which is not gramatically correct.
- When I delete a team member, it seems that all team members get removed. Only the one being deleted should be removed.
- On the edit/add screens, toggling admin/regular roles only works by clicking on the radio button. Ideally, clicking the text next to the button should work as well (for improved usability)

**Comment by amalfra** [comment]
@adamstep Thanks for the feedback. I have fixed text grammer and radio button usability issue. Strange that delete seems to be working correctly when I tried and it's only removing current team member. Did you get any console errors on delete? I am not seeing that issue on my end as not all team members are getting removed.

**Comment by adamstep** [comment]
Hi @amalfra . Your changes look good. I alos figured out that the delete bug happens on Safari, but not on Chrome. From what I could tell from looking at the log, on Chrome, the form submit is caught and prevents the page from re-loading. On Safari, the form submit causes the page to reload, thus losing the state and making it appear that all team members were deleted.

**Comment by amalfra** [comment]
@adamstep ok, it makes sense. I am using chrome. Don't have a mac to test it but I think the latest commit that's pushed will stop the form submit on clicking delete button. could you please check if you don't mind?

**Comment by adamstep** [comment]
that fixed the issue, thanks!

**Comment by amalfra** [comment]
:+1: I am merging this as it's complete

**Pull request merged**
